### ISSUE TITLE
Request for adding Cronos Mainnet Beta to map of zones

### ISSUE THREAD

**Issue by lezzokafka** [mapofzones/cosmos-watcher#1]
Hello Map of Zones team,

Hope this finds you well!

We have launched our EVM chain "[Cronos Mainnet Beta](https://cronos.crypto.org/)" on Nov.9 - a Cosmos-SDK based EVM chain for DeFi, NFTs, and Metaverse with the aims to massively scale the DeFi and decentralized application ecosystem by providing developers with the ability to instantly port apps from Ethereum and EVM-compatible chains.  

We are highly interested in getting Cronos Mainnet Beta to be listed properly on the map of zones and being part of your fantastic network map (in which our main chain Crypto.org is already on).

It would be highly appreciated if you could kindly advise the next steps for this.

**Comment by Raumo0** [comment]
Hello @lezzokafka !

Thanks for the issue! Watcher for cronos blockchain located in cosmos-watcher `cronos` branch: https://github.com/mapofzones/cosmos-watcher/tree/cronos

Currently we have a problem with cronos **codec**. Usually, we use **ModuleBasics** for the register codec.

```
cronosapp "github.com/crypto-org-chain/cronos/app"
cronosapp.ModuleBasics.RegisterInterfaces(interfaceRegistry)
```
https://github.com/mapofzones/cosmos-watcher/blob/0743af1f31424d54ef5d24cf4e1202f552e8b047/pkg/codec/protobuf_codec.go#L25

`github.com/crypto-org-chain/cronos v0.6.1`
https://github.com/mapofzones/cosmos-watcher/blob/0743af1f31424d54ef5d24cf4e1202f552e8b047/go.mod#L25

But we cannot decode data at block height 19:
`unable to resolve type URL /ethermint.crypto.v1.ethsecp256k1.PubKey: tx parse error [cosmos/cosmos-sdk@v0.44.2/x/auth/tx/decoder.go:55]`

Perhaps, we should consider some other dependency, or, on the opposite, there might be a need to fully configure the current ModuleBasics on croons team side.

It would be nice to know how to set up the codec

**Comment by calvinaco** [comment]
Hello @Raumo0 , you should be able to register the codec for `/ethermint.crypto.v1.ethsecp256k1.PubKey` by adding Ethermint dependency here:
https://github.com/tharsis/ethermint/blob/main/crypto/codec/codec.go#L11

**Comment by Raumo0** [comment]
Dear @calvinaco and @lezzokafka,
The patch for cronos cosmos-watcher is ready, then it takes time to sync more than 600k blocks.

Also could you provide a logo for displaying the kronos blockchain logo on mapofzones?
<img width="195" alt="image" src="https://user-images.githubusercontent.com/6114400/146826154-0f5d3486-9154-44a0-bce5-92b59e8a39cb.png">

**Comment by lezzokafka** [comment]
![Icon](https://user-images.githubusercontent.com/51898510/146861468-1c337484-b012-4768-a69c-7f18df499a4a.png)

Hello @Raumo0, thanks a ton! see if the above logo works for you 👯

**Comment by Raumo0** [comment]
> ![Icon](https://user-images.githubusercontent.com/51898510/146861468-1c337484-b012-4768-a69c-7f18df499a4a.png)
> 
> Hello @Raumo0, thanks a ton! see if the above logo works for you 👯

Thank you for the logo!
