### ISSUE TITLE
Can't decode a blocks (functionx)

### ISSUE THREAD

**Issue by wolthrax** [mapofzones/cosmos-watcher#151]
The codec we configured cannot decode a block, we need help setting up the codec.

`unable to resolve type URL /fx.gravity.crosschain.v1.MsgSetOrchestratorAddress: tx parse error [cosmos/cosmos-sdk@v0.45
.5/x/auth/tx/decoder.go:42]`

Working branch: [functionx](https://github.com/mapofzones/cosmos-watcher/tree/functionx)
Current commit: [6aa3014a4aa780693637456da6deec1d7fa95672](https://github.com/mapofzones/cosmos-watcher/tree/6aa3014a4aa780693637456da6deec1d7fa95672)

Line of code, throw error: https://github.com/mapofzones/cosmos-watcher/blob/6aa3014a4aa780693637456da6deec1d7fa95672/pkg/cosmos_sdk/block/parsing/tx_decoding.go#L18

Direct dependencies & replaces:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/6114400/192845764-62210c6d-2b37-4f36-9ad1-73680ba38051.png">

Codec configuration: [pkg/codec/protobuf_codec.go](https://github.com/mapofzones/cosmos-watcher/blob/6aa3014a4aa780693637456da6deec1d7fa95672/pkg/codec/protobuf_codec.go)

Previously we replaced from [block/parsing/msg_parsing.go](https://github.com/mapofzones/cosmos-watcher/blob/6aa3014a4aa780693637456da6deec1d7fa95672/pkg/cosmos_sdk/block/parsing/msg_parsing.go#L18-L19) dependency `transfer "github.com/cosmos/ibc-go/v3/modules/apps/transfer/types"` to `transfer "github.com/functionx/fx-core/v2/x/ibc/applications/transfer/types"`.

Maybe we need to do something like this replace again. But exception throws when block decoding & looks like we need to add some `interfaceRegistry.RegisterInterface` & `interfaceRegistry.RegisterImplementations` at `protobuf_codec.go`

**Comment by zakir-web3** [comment]
Hi, please merge #166 pull request to fix this
